# 02 - Data Cleaning

## Business Objective

The objective of this notebook is to clean and prepare the Walmart Sales Forecasting datasets for exploratory data analysis and predictive modeling. This involves identifying and handling data quality issues, converting data types, treating missing values, validating dataset relationships, and creating a consistent analytical dataset that can be used for feature engineering and model development.

## Analytical Objectives

- Convert date columns to the **datetime** data type.
- Check and confirm missing values in all datasets.
- Handle missing values using appropriate imputation techniques.
- Verify that no duplicate records exist.
- Validate data types for all columns.
- Check for invalid or inconsistent values.
- Investigate negative `Weekly_Sales` values.
- Merge the **train**, **features**, and **stores** datasets.
- Merge the **test**, **features**, and **stores** datasets.
- Verify that all joins preserve the expected number of records.
- Confirm that the cleaned datasets contain no unexpected missing values.
- Save the cleaned datasets for use in Exploratory Data Analysis (EDA) and machine learning.

## Expected Outcome

By the end of this notebook:

- All datasets will have consistent and appropriate data types.
- Missing values will be handled using suitable preprocessing techniques.
- The training and testing datasets will be successfully merged with the external features and store information.
- The cleaned datasets will be validated for quality and consistency.
- The final analytical datasets will be ready for exploratory data analysis, feature engineering, and forecasting model development.

#### Import Libraries

In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

#### Load Datasets

In [3]:
train = pd.read_csv("../data/raw/train.csv")

features = pd.read_csv("../data/raw/features.csv")

stores = pd.read_csv("../data/raw/stores.csv")

test = pd.read_csv("../data/raw/test.csv")

#### Check Data Types

In [4]:
train.dtypes

Store             int64
Dept              int64
Date                str
Weekly_Sales    float64
IsHoliday          bool
dtype: object

In [5]:
features.dtypes

Store             int64
Date                str
Temperature     float64
Fuel_Price      float64
MarkDown1       float64
MarkDown2       float64
MarkDown3       float64
MarkDown4       float64
MarkDown5       float64
CPI             float64
Unemployment    float64
IsHoliday          bool
dtype: object

In [6]:
stores.dtypes

Store    int64
Type       str
Size     int64
dtype: object

####  Convert Date Columns

In [3]:
train["Date"] = pd.to_datetime(train["Date"])
features["Date"] = pd.to_datetime(features["Date"])
test["Date"] = pd.to_datetime(test["Date"])

#### Check Missing Values

In [10]:
train.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

In [11]:
features.isnull().sum()

Store              0
Date               0
Temperature        0
Fuel_Price         0
MarkDown1       4158
MarkDown2       5269
MarkDown3       4577
MarkDown4       4726
MarkDown5       4140
CPI              585
Unemployment     585
IsHoliday          0
dtype: int64

In [9]:
train.isnull().sum().sort_values(ascending=False)

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

#### Missing Value Percentage

In [9]:
missing = (
    train.isnull()
         .sum()
         .to_frame("Missing")
)

missing["Percentage"] = (
    missing["Missing"] / len(train)
) * 100

missing.sort_values(
    "Percentage",
    ascending=False
)

              Missing  Percentage
MarkDown2      310322   73.611025
MarkDown4      286603   67.984676
MarkDown3      284479   67.480845
MarkDown1      270889   64.257181
MarkDown5      270138   64.079038
Store               0    0.000000
Date                0    0.000000
Dept                0    0.000000
Temperature         0    0.000000
Size                0    0.000000
Type                0    0.000000
IsHoliday           0    0.000000
Weekly_Sales        0    0.000000
Fuel_Price          0    0.000000
CPI                 0    0.000000
Unemployment        0    0.000000

#### Handling Missing value

In [12]:
markdown_cols = [
    "MarkDown1",
    "MarkDown2",
    "MarkDown3",
    "MarkDown4",
    "MarkDown5"
]

features[markdown_cols] = features[markdown_cols].fillna(0)

In [13]:
features.head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106,False

In [14]:
features["CPI"].isnull().sum()

np.int64(585)

In [15]:
features["CPI"] = features["CPI"].fillna(
    features["CPI"].median()
)

In [19]:
features.head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106,False

In [20]:
features["Unemployment"].isnull().sum()

np.int64(585)

In [21]:
features["Unemployment"] = features["Unemployment"].fillna(
    features["Unemployment"].median()
)

In [22]:
features.head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106,False

#### Check Duplicate Records

In [10]:
train.duplicated().sum()

np.int64(0)

In [23]:
features.duplicated().sum()

np.int64(0)

In [24]:
stores.duplicated().sum()

np.int64(0)

#### Negative Weekly Sales

In [12]:
(train["Weekly_Sales"] < 0).sum()

np.int64(1285)

In [13]:
train.loc[
    train["Weekly_Sales"] < 0,
    ["Store", "Dept", "Date", "Weekly_Sales"]
].head()

      Store  Dept       Date  Weekly_Sales
846       1     6 2012-08-10       -139.65
2384      1    18 2012-05-04         -1.27
6048      1    47 2010-02-19       -863.00
6049      1    47 2010-03-12       -698.00
6051      1    47 2010-10-08        -58.00

#### Validate Store Types

In [14]:
train["Type"].value_counts()

Type
A    215478
B    163495
C     42597
Name: count, dtype: int64

#### Validate Holiday Values

In [15]:
train["IsHoliday"].value_counts()

IsHoliday
False    391909
True      29661
Name: count, dtype: int64

#### Merge Datasets

In [25]:
train = train.merge(
    stores,
    on="Store",
    how="left"
)

In [26]:
train = train.merge(
    features,
    on=["Store", "Date", "IsHoliday"],
    how="left"
)

#### Verify Merge Results

In [27]:
train.shape

(421570, 16)

In [28]:
train.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Type,Size,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,1,1,2010-02-05,24924.50,False,A,151315,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106
1,1,1,2010-02-12,46039.49,True,A,151315,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106
2,1,1,2010-02-19,41595.55,False,A,151315,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106
3,1,1,2010-02-26,19403.54,False,A,151315,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106
4,1,1,2010-03-05,21827.90,False,A,151315,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106

In [31]:

#Check for missing store information.
train["Type"].isnull().sum()

np.int64(0)

In [32]:
#Check missing feature values.
train["Temperature"].isnull().sum()

np.int64(0)

#### Final Missing Value Check

In [33]:
missing = (
    train.isnull()
         .sum()
         .sort_values(ascending=False)
)

missing

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
Type            0
Size            0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
dtype: int64

#### Save the Cleaned Dataset

In [34]:
train.to_csv(
    "../data/processed/train_clean.csv",
    index=False
)

### Key Observations

- Date columns were converted to the correct datetime format.
- Promotional MarkDown columns contained a high proportion of missing values, which were interpreted as weeks without promotions and replaced with 0.
- Missing values in CPI and Unemployment were imputed using the median to preserve the overall distribution.
- No duplicate records were found after cleaning.
- Negative weekly sales were retained because they likely represent product returns or financial adjustments.
- Sales, store, and external feature datasets were successfully merged into a single analytical table.
- The final dataset contains complete store information and external factors required for forecasting.

### Executive Summary

This notebook prepared the Walmart Sales Forecasting dataset for analysis and predictive modeling. Data types were validated, missing values were handled using business-appropriate strategies, duplicate records were removed, and negative sales transactions were investigated.

The sales, store, and feature datasets were successfully merged into a unified analytical dataset. The resulting dataset is clean, consistent, and ready for exploratory data analysis, feature engineering, and machine learning model development.